title: "4RKS"
description: "Независимый онлайн-журнал о видеоиграх: обзоры, аналитика игровой индустрии, интервью с разработчиками и гейм-дизайн."
url: "https://4rks.ru"
baseurl: ""
lang: ru
author: 4RKS

permalink: /:categories/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

twitter:
  card: summary_large_image

social:
  name: 4RKS

markdown: kramdown
